### PR TITLE
Add timer support to Gauge, Summary and Histogram metric types.

### PR DESCRIPTION
**Pull request by MarcoWesterink**
Makes it easier and more readable to use gauge timers.

### CODE REVIEW

**Comment by sandersaares** [comment]
Thank you for the contribution!

I am happy to merge the IDisposable addition but not the addition to the documentation, as this timer feature is a bit of a special case legacy feature that I do not want to promote much in the documentation.

To be suitable for general purpose usage, the timer feature would need to be more flexible and offer a bit more utility (e.g. enabling timer intervals to be represented as Summary or Histogram, not only Gauge; see https://github.com/prometheus/client_golang/blob/master/prometheus/timer.go). If you are interested in extending the timer feature with Summary and Histogram support (and doing relevant refactoring such as moving it out of Gauge class), I would be happy to merge such a PR.

Please let me know of your wishes - do you wish to extend this PR to also cover the extension to Histogram/Summary? Or is that not of interest and you wish to keep this PR scope to only the IDisposable extension? I am happy to merge it either way, just depends on how far you wish to take it.

**Comment by MarcoWesterink** [comment]
Sorry for the delayed response. I've tried to extract the timer to support Gauge, Summary and Histogram. I came to the conclusion that a histogram was actually what I needed ;-). Feel free to comment on the implementation.

**Comment by MarcoWesterink** [comment]
Any interest in merging this one?

**Comment by sandersaares** [comment]
Apologies for the delay. Thanks again for the contribution!

**Comment by sandersaares** [comment]
Version 3.0.0 is now published, with this change included.

**Pull request merged**
