### PR TITLE
Allow additional labels based on custom HTTP request inspection

### PR DESCRIPTION
**Pull request by askazakov**
see https://github.com/prometheus-net/prometheus-net/issues/259

### CODE REVIEW

**Comment by joebettger** [comment]
This PR and PR #304 would be tremendously helpful to my current project. I would be happy to assist in moving this along if there's some way I can help.

**Comment by askazakov** [comment]
@sandersaares please look at this and provide any feedback. Should I improve something? Or I wrong totally and should close this pr

**Comment by prostakov** [comment]
Guys, are there any updates on this? I could really use this feature...

**Comment by sandersaares** [comment]
This has been superseded by the `AddCustomLabel()` feature, currently available in v6.0.0 prerelease packages on nuget.org. Please let me know if the implementation satisfies your requirements.

**Pull request closed without merging**
