### PR TITLE
Add netcoreapp3.1 target

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Thanks so much for raising this PR!  Just spent the morning wondering why things weren't working and I suspect this is the reason 😄

**Comment by sungam3r** [comment]
@sandersaares Any progress on this?

**Comment by sungam3r** [comment]
Relates to #194 . @sandersaares Do I need to also add dependencies groups in nuspec?

**Comment by sandersaares** [comment]
What exactly does the change in this PR accomplish? The library is already compatible with ASP.NET Core 3.1 as far as I know. Are you having some problem using it with ASP.NET Core 3.1, @sungam3r?

**Comment by sandersaares** [comment]
@johnnyreilly the stack trace you pasted indicates that you are not using prometheus-net but rather the Prometheus integration in App Metrics, which is a different library altogether and not related to prometheus-net.

**Comment by sungam3r** [comment]
> What exactly does the change in this PR accomplish? The library is already compatible with ASP.NET Core 3.1 as far as I know. Are you having some problem using it with ASP.NET Core 3.1, @sungam3r?

No problems yet. I migrate the backend to 3.1 and noticed that this package targets 3.0. I thought that it would not hurt to explicitly specify the 3.1 target as well especially since it is LTS.

**Comment by kerams** [comment]
>I thought that it would not hurt to explicitly specify the 3.1 target as well

Well, it's going to increase the Nuget package size while providing no benefit at all.

**Comment by sandersaares** [comment]
Since the present state of things does not lead to any issues, I will not merge this PR that would include both 3.0 and 3.1 binaries in the package, as it would not produce any benefit.

It is true that .NET Core 3.0 is end-of-life in approximately 1 month. However, on a technical level that does not strictly matter for prometheus-net given that you can install it fine into a 3.1 project even if it targets 3.0 internally. I imagine in a future package version the target will change to 3.1 instead of the current 3.0, to track the supported .NET Core versions.

**Comment by johnnyreilly** [comment]
@sandersaares you were right; this is actually the issue I'm facing: https://github.com/AppMetrics/AppMetrics/issues/396

**Pull request closed without merging**
